### ISSUE TITLE
Dockerd as a python flask server:

### ISSUE THREAD

**Issue by ForkInABlender** [docker/roadmap#698]
[dockerd_mimick.py](https://raw.githubusercontent.com/ForkInABlender/ChatGPT_solutions_produced_from_simple_prompt/2024_08/integrations/python%20based%20dockerd/dockerd_mimick.py)

**Tell us about your request**
A clear and concise description of what you want to happen or the change you would like to see

Over the last year, I was exploring what I could do with a flask server. GPT & I by inquiry have come close to a poorly designed but half working model. It won’t let “docker run” function due to not knowing how the grpc is used.

If one were to flesh out the flask based dockerd mimick, the goal in mind was functionality & flexibility to give dockerd a way to run on cellphones & smart watches.  I ask because I am trying to setup a AI that can run on any hardware.

**Which service(s) is this request for?**
Let us know which product(s) you want this for?

This is requested for dockerd as a whole. But for it to be also able to have a flask setup that works for android devices. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I was aiming for a python flask server version of dockerd that performed similar enough to dockerd that was initially compiled from golang. I got hung up at that part of "docker run" due to lack of knowing the native "docker run" implementation. 

**Are you currently working around the issue?**

No, as that requires more in depth knowledge of golang, dockerd source code, etc. 
```[tasklist]
### Tasks
- [ ] * flask server handles while directing docker clients to https://127.0.0.1:2375 to mimick function responses
- [ ] * TCP tunnel upgrade request always true even for flask sockets
- [ ] * must use python code to mimick all functionality via flask server
- [ ] * must not compile down and then wrap with return
- [ ] * must not use rpc of any kind but python code to imitate
- [ ] * flask sockets (optional)
- [ ] * must not use socat linux binary or similar
```
