### ISSUE TITLE
323232

### ISSUE THREAD

**Issue by lauraloba** [docker/roadmap#707]
**Tell us about your request**
A clear and concise description of what you want to happen or the change you would like to see

**Which service(s) is this request for?**
Let us know which product(s) you want this for?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

**Are you currently working around the issue?**
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/docker/roadmap/issues/44
- [ ] https://github.com/docker/roadmap/issues/665
- [ ] https://github.com/docker/roadmap/issues/312
- [ ] https://github.com/docker/roadmap/issues/663
- [ ] https://github.com/docker/roadmap/issues/706
```

```[tasklist]
### Tasks
- [ ] https://github.com/docker/roadmap/issues/613
- [ ] https://github.com/docker/roadmap/issues/665
- [ ] https://github.com/docker/roadmap/issues/312
- [ ] https://github.com/docker/roadmap/issues/663
- [ ] https://github.com/docker/roadmap/issues/702
- [ ] https://github.com/docker/roadmap/issues/701
- [ ] https://github.com/docker/roadmap/issues/473
- [ ] https://github.com/docker/roadmap/issues/413
```

```[tasklist]
### Tasks
```
